language: csharp
solution: src/dotnet-unit-convertor.json

matrix:
  include:
    - dotnet: 1.0.1
      mono: none
      env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
    - mono: latest
